from Animal import Animal
from Caballo import Caballo
from Cocodrilo import Cocodrilo
from Pez import Pez
from Escarabajo import Escarabajo
from Pato import Pato

#Codigo principal
print("CABALLO")
ObjCaballo = Caballo("Caballo", "14 años", "heno", "llanura", "Medio", "Blanco")
ObjCaballo.imprimir()
ObjCaballo.moverse()
ObjCaballo.comunicacion()
ObjCaballo.alimentarse()
ObjCaballo.reproduccion()
ObjCaballo.adaptacion()
ObjCaballo.instintos()
ObjCaballo.descanso()
ObjCaballo.sueño()
ObjCaballo.interaccionSocial()

print("\nCOCODRILO")
ObjCocodrilo = Cocodrilo("Cocodrilo", "30 años", "carne", "llanura", "Pequeño", "verde")
ObjCocodrilo.imprimir()
ObjCocodrilo.moverse()
ObjCocodrilo.comunicacion()
ObjCocodrilo.alimentarse()
ObjCocodrilo.reproduccion()
ObjCocodrilo.adaptacion()
ObjCocodrilo.instintos()
ObjCocodrilo.descanso()
ObjCocodrilo.sueño()
ObjCocodrilo.interaccionSocial()

print("\nPEZ")
ObjPez = Pez("Pez", "2 años", "plancton", "rio", "Pequeño", "naranja")
ObjPez.imprimir()
ObjPez.moverse()
ObjPez.comunicacion()
ObjPez.alimentarse()
ObjPez.reproduccion()
ObjPez.adaptacion()
ObjPez.instintos()
ObjPez.descanso()
ObjPez.sueño()
ObjPez.interaccionSocial()

print("\nESCARABAJO")
ObjEscarabajo = Escarabajo("Escarabajo", "6 años", "hojas", "montaña", "Pequeño", "rojo")
ObjEscarabajo.imprimir()
ObjEscarabajo.moverse()
ObjEscarabajo.comunicacion()
ObjEscarabajo.alimentarse()
ObjEscarabajo.reproduccion()
ObjEscarabajo.adaptacion()
ObjEscarabajo.instintos()
ObjEscarabajo.descanso()
ObjEscarabajo.sueño()
ObjEscarabajo.interaccionSocial()

print("\nPATO")
ObjPato = Pato("Pato", "5 años", "plantas", "montaña", "Pequeño", "rojo")
ObjPato.imprimir()
ObjPato.moverse()
ObjPato.comunicacion()
ObjPato.alimentarse()
ObjPato.reproduccion()
ObjPato.adaptacion()
ObjPato.instintos()
ObjPato.descanso()
ObjPato.sueño()
ObjPato.interaccionSocial()